{
 "title": "Detector DDoS",
 "time": { "from": "2024-06-23T11:45:20.000Z", "to": "2024-06-23T12:27:22.000Z" },
 "panels": [
  {
   "title": "Flujos registrados",
   "type": "timeseries",
   "description": "Tipos de flujos por cada registro de cierto número de paquetes. La frecuencia en la que se capturan los paquetes se puede modificar. Actualmente: 5000",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timezone('Europe/Madrid', timestamp AT TIME ZONE 'Europe/Madrid') as timestamp,\r\n  benign,\r\n  ldap,\r\n  mssql,\r\n  syn,\r\n  udp\r\nFROM predicciones"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  label\r\nFROM\r\n  predicciones\r\nORDER BY\r\n  timestamp DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Ataques DDoS detectados",
   "type": "stat",
   "description": "Número total de ataques DDoS detectados en las últimas 200 predicciones",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(label)\r\nFROM predicciones\r\nWHERE label = true\r\nLIMIT 200"
    }
   ]
  },
  {
   "title": "Paquetes/captura",
   "type": "stat",
   "description": "Número medio de paquetes por captura",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pkts/c" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(total_paquetes) FROM predicciones LIMIT 50 "
    }
   ]
  },
  {
   "title": "Paquetes analizados",
   "type": "timeseries",
   "description": "Registro de paquetes analizados (Max: 5000)",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timezone('Europe/Madrid', timestamp AT TIME ZONE 'Europe/Madrid') as timestamp,\r\n  total_paquetes\r\nFROM predicciones"
    }
   ]
  },
  { "type": "speakyourcode-button-panel", "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 } },
  {
   "title": "Porcentaje de flujos",
   "type": "piechart",
   "description": "Porcentaje del total de los flujos de las 20 últimas predicciones",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(benign) AS total_benign,\r\n       SUM(ldap) AS total_ldap,\r\n       SUM(mssql) AS total_mssql,\r\n       SUM(syn) AS total_syn,\r\n       SUM(udp) AS total_udp\r\nFROM (\r\n    SELECT benign, ldap, mssql, syn, udp\r\n    FROM predicciones\r\n    ORDER BY id DESC\r\n    LIMIT 20\r\n) AS ultimas_20_filas;\r\n"
    }
   ]
  },
  {
   "type": "gauge",
   "description": "Número total de paquetes analizados",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(total_paquetes) FROM predicciones LIMIT 50 "
    }
   ]
  }
 ]
}